spring:
  docker:
    compose:
      file: ../docker-compose.yml
      lifecycle-management: start-only
  jpa:
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
