package com.libseat.entity;

public enum NotificationType {
    RESERVATION_SUCCESS, RESERVATION_CANCELLED, CHECKIN_REMINDER,
    NO_SHOW_WARNING, ACCOUNT_LOCKED, ACCOUNT_SUSPENDED,
    WAITLIST_AVAILABLE, RENEWAL_SUCCESS, SYSTEM
}
